server:
  port: ${port} #\u670D\u52A1\u7AEF\u53E3
spring:
  application:
    name: itcast-microservice-manager #\u6307\u5B9A\u670D\u52A1\u540D
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false


eureka:
  client:
    registerWithEureka: true #\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D\uFF0C\u9ED8\u8BA4\u4E3Atrue
    fetchRegistry:  true  #\u662F\u5426\u4ECEEureka\u4E2D\u83B7\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C\u9ED8\u8BA4\u4E3Atrue
    serviceUrl: #Eureka\u5BA2\u6237\u7AEF\u4E0EEureka\u670D\u52A1\u7AEF\u8FDB\u884C\u4EA4\u4E92\u7684\u5730\u5740
      defaultZone: http://127.0.0.1:6868/eureka,http://127.0.0.1:6869/eureka
  instance:
    prefer-ip-address:  true  #\u5C06\u81EA\u5DF1\u7684ip\u5730\u5740\u6CE8\u518C\u5230Eureka\u670D\u52A1\u4E2D
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #\u6307\u5B9A\u5B9E\u4F8Bid
#itcast-microservice-item:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    root: DEBUG
  #    org.springframework.web: DEBUG
  file: /log/log/my_consume.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"


